name: mongo_db_query
version: 0.1.0-1.5.dev
description: Query and aggregation utilities for working with MongoDb
homepage: https://github.com/mongo-dart/mongo_db_query
funding:
  - https://www.paypal.com/donate?hosted_button_id=YRUNF9YWKX2NW
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bson: ^5.0.3
  meta: ^1.9.0
  fixnum: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
