name: mongo_db_query
version: 0.1.0-1.0.dev
description: Query and aggregation utilities for working with MongoDb
homepage: https://github.com/mongo-dart/mongo_db_query
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bson: ^5.0.0
  meta: ^1.9.0
  fixnum: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
